version: "3"

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
      args:
        VARIANT: "3.10"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PGPASSWORD: postgres
      # PRE_COMMIT_HOME: 

  elasticsearch:
    image: bitnami/elasticsearch
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  
  logstash:
    image: bitnami/logstash
    command: logstash -f /usr/share/logstash/config.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config.conf:/usr/share/logstash/config.conf

  kibana:
    container_name: kibana
    image: bitnami/kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
  elasticsearch-data:
    driver: local
